import type { Course } from "./types";

function C(
  code: string,
  name_ar: string,
  name_en: string,
  year: number,
  sem: number,
  th: number,
  lab: number,
  instructor_id: string,
  desc_ar: string,
  desc_en: string,
  prereq: string | null = null,
): Course {
  return {
    code,
    name_ar,
    name_en,
    year_level: year,
    semester: sem,
    hours_theory: th,
    hours_lab: lab,
    credits: th + lab,
    desc_ar,
    desc_en,
    instructor_id,
    prereq,
  };
}

export const COURSES: Course[] = [
  C("MEA101", "مدخل إلى علم الاقتصاد", "Introduction to economics", 1, 1, 4, 0, "f-deeb",
    "المشكلة الاقتصادية، الندرة، أنظمة الإنتاج، السوق مقابل التخطيط، وحدود النموذج كأداة للفهم.",
    "The economic problem, scarcity, production systems, market versus planning, and the model as a tool of thought."),
  C("MEA111", "رياضيات اقتصادية 1", "Mathematical economics I", 1, 1, 2, 2, "f-khoury",
    "الدوال، المشتقات، الأمثلة المقيّدة، مرونات، ومقدمة للمصفوفات كما يحتاجها الاقتصادي.",
    "Functions, derivatives, constrained optimisation, elasticities, and matrices as an economist uses them."),
  C("MEA121", "إحصاء وصفي", "Descriptive statistics", 1, 1, 2, 2, "f-barakat",
    "توزيعات، مقاييس نزعة وتشتت، الارتباط، والعرض البياني للبيانات الاقتصادية.",
    "Distributions, location and spread, correlation, and graphical display of economic data."),
  C("MEA131", "مبادئ المحاسبة", "Principles of accounting", 1, 1, 2, 2, "f-shaheen",
    "القيد المزدوج، القوائم المالية، وقراءة أرقام المنشأة قبل الانتقال إلى الحسابات القومية.",
    "Double entry, financial statements, and reading a firm before moving to national accounts."),
  C("MEA141", "برمجة للتحليل الاقتصادي 1", "Computing for economics I", 1, 1, 1, 3, "f-kadmani",
    "Python: بنى البيانات، التحكم، الدوال، وقراءة ملفات CSV للمؤشرات الاقتصادية.",
    "Python: data structures, control flow, functions, and reading CSV indicator files."),
  C("MEA191", "لغة أجنبية اقتصادية 1", "Economic English I", 1, 1, 4, 0, "f-atri",
    "قراءة نصوص اقتصادية قصيرة وكتابة فقرة تحليلية بالإنكليزية.",
    "Reading short economic texts and writing an analytical paragraph in English."),

  C("MEA102", "مبادئ الاقتصاد الكلّي", "Principles of macroeconomics", 1, 2, 4, 0, "f-abdelnour",
    "الدخل القومي، الاستهلاك والاستثمار، النقود، والتضخم والبطالة في إطار مبسّط.",
    "National income, consumption and investment, money, inflation and unemployment in a simple frame.", "MEA101"),
  C("MEA112", "رياضيات اقتصادية 2", "Mathematical economics II", 1, 2, 2, 2, "f-khoury",
    "تكامل، معادلات فرقية تمهيدية، ومتتاليات كما تظهر في نماذج النمو.",
    "Integrals, introductory difference equations, and sequences as they appear in growth models.", "MEA111"),
  C("MEA122", "نظرية الاحتمالات", "Probability", 1, 2, 2, 2, "f-barakat",
    "المتغيرات العشوائية، التوزيعات الشائعة في الاقتصاد، والتوقع المشروط.",
    "Random variables, distributions common in economics, and conditional expectation.", "MEA121"),
  C("MEA132", "مدخل إلى النمذجة الاقتصادية", "Introduction to economic modelling", 1, 2, 2, 2, "f-harfoush",
    "ما النموذج، فروضه، حدوده، وتمرين أول على بناء علاقة قابلة للقياس.",
    "What a model is, its assumptions and limits, and a first exercise in a measurable relationship.", "MEA101"),
  C("MEA142", "تطبيقات حاسوبية", "Applied computing", 1, 2, 1, 3, "f-kadmani",
    "تنظيف البيانات، الرسم، وتصدير جداول قابلة لإعادة التشغيل.",
    "Cleaning data, plotting, and exporting reproducible tables.", "MEA141"),
  C("MEA192", "لغة أجنبية اقتصادية 2", "Economic English II", 1, 2, 4, 0, "f-atri",
    "تلخيص ورقة قصيرة وعرض شفهي لمؤشر اقتصادي.",
    "Summarising a short paper and presenting an economic indicator.", "MEA191"),

  C("MEA201", "تحليل اقتصادي جزئي", "Microeconomic analysis", 2, 1, 2, 2, "f-deeb",
    "تفضيلات، طلب، إنتاج وتكلفة، وتوازن المنشأة في أسواق مختلفة.",
    "Preferences, demand, production and cost, and firm equilibrium across market structures.", "MEA101"),
  C("MEA211", "جبر خطي للاقتصاديين", "Linear algebra for economists", 2, 1, 2, 2, "f-khoury",
    "فضاءات، قيم ذاتية، أنظمة معادلات، ومدخلات-مخرجات.",
    "Vector spaces, eigenvalues, linear systems, and input–output.", "MEA112"),
  C("MEA221", "إحصاء استدلالي", "Statistical inference", 2, 1, 2, 2, "f-barakat",
    "تقدير، اختبار فرضيات، فترات ثقة، ومقدمة للانحدار كأداة وصف.",
    "Estimation, hypothesis tests, confidence intervals, and regression as description.", "MEA122"),
  C("MEA231", "نقود ومصارف", "Money and banking", 2, 1, 2, 2, "f-shaheen",
    "عرض النقود، الجهاز المصرفي، وأدوات السياسة النقدية.",
    "Money supply, the banking system, and monetary-policy instruments.", "MEA102"),
  C("MEA241", "اقتصاد قياسي تمهيدي", "Introductory econometrics", 2, 1, 2, 2, "f-harfoush",
    "الانحدار البسيط، فروض غاوس-ماركوف، والقراءة النقدية لمخرجات التقدير.",
    "Simple regression, Gauss–Markov assumptions, and a critical reading of output.", "MEA221"),
  C("MEA291", "لغة أجنبية اقتصادية 3", "Economic English III", 2, 1, 4, 0, "f-atri",
    "كتابة مذكرة سياسة من صفحة واحدة.",
    "Writing a one-page policy note.", "MEA192"),

  C("MEA202", "تحليل اقتصادي كلّي", "Macroeconomic analysis", 2, 2, 2, 2, "f-abdelnour",
    "IS-LM في اقتصاد مفتوح مبسّط، العرض الكلّي، ومنحنى فيليبس.",
    "IS–LM in a small open economy, aggregate supply, and the Phillips curve.", "MEA102"),
  C("MEA212", "معادلات تفاضلية وديناميك", "Differential equations & dynamics", 2, 2, 2, 2, "f-khoury",
    "الاستقرار، مخططات الطور، ونماذج نمو مستمر مبسّطة.",
    "Stability, phase diagrams, and simple continuous-time growth.", "MEA211"),
  C("MEA222", "مالية عامة", "Public finance", 2, 2, 2, 2, "f-shaheen",
    "النفقات، الضرائب، العجز، والكفاءة مقابل العدالة.",
    "Expenditure, tax, deficit, and efficiency versus equity.", "MEA201"),
  C("MEA232", "قانون وتشريع اقتصادي", "Economic law", 2, 2, 4, 0, "f-deeb",
    "إطار العقود والشركات والتشريع المالي بقدر ما يحتاجه النموذج والجدوى.",
    "Contracts, companies and fiscal legislation as far as modelling and feasibility require.", "MEA101"),
  C("MEA242", "برمجة إحصائية", "Statistical programming", 2, 2, 1, 3, "f-kadmani",
    "R: إطارات البيانات، الانحدار، وإعادة التشغيل من ملف واحد.",
    "R: data frames, regression, and a one-file reproducible script.", "MEA141"),
  C("MEA292", "لغة أجنبية اقتصادية 4", "Economic English IV", 2, 2, 4, 0, "f-atri",
    "قراءة ورقة قياسية قصيرة وعرض فروضها.",
    "Reading a short empirical paper and presenting its assumptions.", "MEA291"),

  C("MEA301", "اقتصاد قياسي 1 — الانحدار", "Econometrics I — regression", 3, 1, 2, 2, "f-harfoush",
    "المتعدد، المتغيرات الوهمية، التشخيص، والارتباط الذاتي المبدئي.",
    "Multiple regression, dummies, diagnostics, and a first look at serial correlation.", "MEA241"),
  C("MEA311", "الاقتصاد الرياضي", "Mathematical economics", 3, 1, 2, 2, "f-khoury",
    "توازن عام مبسّط، أمثلة ديناميكية، ونظرية المباريات التمهيدية.",
    "Small general equilibrium, dynamic examples, and introductory game theory.", "MEA211"),
  C("MEA321", "الحسابات القومية", "National accounts", 3, 1, 2, 2, "f-ismail",
    "نظام الحسابات، الناتج، الدخل، ومصفوفة المحاسبة الاجتماعية تمهيدياً.",
    "The accounts system, output and income, and a first social accounting matrix.", "MEA202"),
  C("MEA331", "علاقات اقتصادية دولية", "International economics", 3, 1, 2, 2, "f-atri",
    "التجارة، ميزان المدفوعات، وسعر الصرف في اقتصاد صغير.",
    "Trade, the balance of payments, and the exchange rate in a small economy.", "MEA202"),
  C("MEA341", "قضايا اقتصادية معاصرة", "Contemporary economic issues", 3, 1, 4, 0, "f-atri",
    "ملفات سورية وإقليمية تُقرأ بأدوات البرنامج: تضخم، طاقة، إعادة إعمار.",
    "Syrian and regional files read with programme tools: inflation, energy, reconstruction.", "MEA202"),

  C("MEA302", "اقتصاد قياسي 2 — السلاسل", "Econometrics II — time series", 3, 2, 2, 2, "f-barakat",
    "الاستقرار، التكامل المشترك، VAR، والتنبؤ قصير الأجل.",
    "Stationarity, cointegration, VAR, and short-horizon forecasts.", "MEA301"),
  C("MEA312", "بحوث العمليات", "Operations research", 3, 2, 2, 2, "f-khoury",
    "البرمجة الخطية، النقل، والقرار متعدد المعايير في مسائل تخطيط.",
    "Linear programming, transport, and multi-criteria decisions in planning problems.", "MEA211"),
  C("MEA322", "التنمية والتخطيط", "Development and planning", 3, 2, 4, 0, "f-ismail",
    "نماذج النمو، فجوات التمويل، وتخطيط القطاعات في اقتصاد متعافٍ.",
    "Growth models, financing gaps, and sector planning in a recovering economy.", "MEA321"),
  C("MEA332", "دراسات الجدوى", "Feasibility studies", 3, 2, 2, 2, "f-ismail",
    "التدفقات، الخصم، الحساسية، والمخاطر في مشروع عام أو خاص.",
    "Cash flows, discounting, sensitivity and risk in a public or private project.", "MEA222"),
  C("MEA342", "نمذجة الاقتصاد الكلّي", "Macroeconomic modelling", 3, 2, 2, 2, "f-abdelnour",
    "نموذج كلّي صغير قابل للمعايرة، صدمات، ومسارات بديلة.",
    "A small calibratable macro model, shocks, and alternative paths.", "MEA202"),

  C("MEA401", "اقتصاد قياسي متقدم", "Advanced econometrics", 4, 1, 2, 2, "f-harfoush",
    "اللوحي، الآني، والمتغيرات الأداتية، مع تطبيق سوري واحد على الأقل.",
    "Panels, simultaneous equations and instruments, with at least one Syrian application.", "MEA302"),
  C("MEA411", "محاكاة ونماذج ديناميكية", "Simulation & dynamic models", 4, 1, 2, 2, "f-abdelnour",
    "محاكاة مونت كارلو، نماذج المخزون والتدفق، واختبار السياسات.",
    "Monte Carlo, stock–flow models, and policy experiments.", "MEA342"),
  C("MEA421", "تحليل السياسات العامة", "Public policy analysis", 4, 1, 2, 2, "f-shaheen",
    "دورة السياسة، تقييم الأثر، وكتابة التوصية المدعومة بنموذج.",
    "The policy cycle, impact evaluation, and a model-backed recommendation.", "MEA222"),
  C("MEA431", "اقتصاد الطاقة والموارد", "Energy and resource economics", 4, 1, 2, 2, "f-atri",
    "الطلب على الطاقة، التسعير، والانتقال في اقتصاد منتج للنفط.",
    "Energy demand, pricing, and transition in an oil-producing economy.", "MEA331"),
  C("MEA491", "مشروع التخرج 1", "Graduation project I", 4, 1, 1, 3, "f-deeb",
    "اقتراح البحث، المراجعة، وبيانات قابلة للتكرار. يُناقش المقترح أمام اللجنة.",
    "Proposal, literature, and replicable data. The proposal is defended before the committee.", "MEA301"),

  C("MEA402", "بيانات ضخمة وتعلّم آلي", "Economic data & machine learning", 4, 2, 2, 2, "f-kadmani",
    "تجميع، تنظيم، نماذج تنبؤ تمهيدية، وحدود التعلّم الآلي أمام النموذج الهيكلي.",
    "Ingest, tidy, introductory prediction models, and the limits of ML versus a structural model.", "MEA242"),
  C("MEA412", "سيناريوهات الاقتصاد السوري", "Scenarios for the Syrian economy", 4, 2, 2, 2, "f-abdelnour",
    "بناء ثلاثة مسارات على الأقل (أساس، إصلاح، صدمة) مع افتراضات معلنة.",
    "At least three paths (baseline, reform, shock) with stated assumptions.", "MEA342"),
  C("MEA422", "صناعة القرار الاقتصادي", "Economic decision-making", 4, 2, 2, 2, "f-shaheen",
    "من النموذج إلى المذكرة: جمهور القرار، التحفظ، وما لا يقوله الرقم.",
    "From model to note: the decision audience, caveats, and what a number does not say.", "MEA421"),
  C("MEA432", "منهجية البحث العلمي", "Research methods", 4, 2, 2, 2, "f-deeb",
    "سؤال البحث، التصميم، الأخلاقيات، والتوثيق في الاقتصاد التطبيقي.",
    "Research question, design, ethics, and documentation in applied economics.", "MEA301"),
  C("MEA492", "مشروع التخرج 2", "Graduation project II", 4, 2, 1, 3, "f-deeb",
    "التقدير، الكتابة، والمناقشة العلنية. المشروع ليس متطلباً شكلياً بل نواة دراسة قابلة للتوظيف.",
    "Estimation, writing, and a public defence. The project is a usable study, not a formality.", "MEA491"),
];
