import type { Person } from "./types";

function F(
  id: string,
  name_ar: string,
  name_en: string,
  title_ar: string,
  title_en: string,
  office: string,
  research_ar: string,
  research_en: string,
  bio_ar: string,
  bio_en: string,
  course_codes: string,
): Person {
  return {
    id,
    kind: "faculty",
    name_ar,
    name_en,
    year_level: null,
    student_no: null,
    cohort: null,
    title_ar,
    title_en,
    office,
    email: `${id.replace("f-", "")}@eco.damascusuniversity.edu.sy`,
    bio_ar,
    bio_en,
    research_ar,
    research_en,
    course_codes,
    advisor_id: null,
  };
}

function S(
  id: string,
  name_ar: string,
  name_en: string,
  year: number,
  no: string,
  cohort: string,
  advisor_id: string,
  bio_ar: string,
  bio_en: string,
): Person {
  return {
    id,
    kind: "student",
    name_ar,
    name_en,
    year_level: year,
    student_no: no,
    cohort,
    title_ar: null,
    title_en: null,
    office: null,
    email: `${no.toLowerCase()}@stud.damascusuniversity.edu.sy`,
    bio_ar,
    bio_en,
    research_ar: "",
    research_en: "",
    course_codes: "",
    advisor_id,
  };
}

export const FACULTY: Person[] = [
  F(
    "f-harfoush",
    "د. سليم حرفوش",
    "Dr. Salim Harfoush",
    "منسّق البرنامج — اقتصاد قياسي",
    "Programme coordinator — Econometrics",
    "مكتب 214",
    "القياس الاقتصادي التطبيقي، سياسات الاقتصاد الكلّي، تقييم الأثر.",
    "Applied econometrics, macro policy, impact evaluation.",
    "يشرف على البرنامج منذ إحداثه. كوّن مسار القياس في الكلية ويركّز على ربط أدوات التقدير بمسائل السياسة السورية.",
    "Has coordinated the programme since it opened. Built the econometrics track and ties estimation tools to Syrian policy questions.",
    "MEA241,MEA301,MEA401",
  ),
  F(
    "f-abdelnour",
    "د. رنا عبد النور",
    "Dr. Rana Abdelnour",
    "أستاذ مساعد — اقتصاد كلّي ونمذجة",
    "Assistant professor — Macroeconomics & modelling",
    "مكتب 221",
    "نماذج DSGE المبسّطة، الدورات، سيناريوهات إعادة الإعمار.",
    "Small DSGE models, cycles, reconstruction scenarios.",
    "تدرّس التحليل الكلّي والنمذجة الديناميكية، وتشرف على مشاريع السيناريوهات للاقتصاد السوري.",
    "Teaches intermediate macro and dynamic modelling; supervises scenario projects on the Syrian economy.",
    "MEA102,MEA202,MEA342,MEA412",
  ),
  F(
    "f-khoury",
    "د. فادي خوري",
    "Dr. Fadi Khoury",
    "مدرّس — رياضيات اقتصادية",
    "Lecturer — Mathematical economics",
    "مكتب 118",
    "التحسين الديناميكي، التوازن العام، الجبر الخطي للتطبيقات.",
    "Dynamic optimisation, general equilibrium, linear algebra for applications.",
    "يبني الأساس الرياضي للدفعة من السنة الأولى حتى الاقتصاد الرياضي في السنة الثالثة.",
    "Builds the mathematical spine of the cohort, from year one through mathematical economics in year three.",
    "MEA111,MEA112,MEA211,MEA212,MEA311",
  ),
  F(
    "f-barakat",
    "د. لينا بركات",
    "Dr. Lina Barakat",
    "مدرّسة — إحصاء تطبيقي",
    "Lecturer — Applied statistics",
    "مكتب 119",
    "الاستدلال، العينات، السلاسل الزمنية التمهيدية.",
    "Inference, sampling, introductory time series.",
    "مسؤولة مختبر الإحصاء، وتدرّب الطلاب على التصميم قبل الانتقال إلى القياس.",
    "Runs the statistics lab and trains students in design before they move to econometrics.",
    "MEA121,MEA122,MEA221,MEA302",
  ),
  F(
    "f-shaheen",
    "د. ماهر شاهين",
    "Dr. Maher Shaheen",
    "أستاذ مساعد — مالية عامة وسياسات",
    "Assistant professor — Public finance & policy",
    "مكتب 230",
    "الإنفاق العام، الضرائب، تقييم السياسات.",
    "Public expenditure, taxation, policy evaluation.",
    "يربط المالية العامة بأدوات القياس ويشرف على مذكرات السياسات في السنة الرابعة.",
    "Connects public finance to measurement tools and supervises year-four policy notes.",
    "MEA222,MEA421,MEA422",
  ),
  F(
    "f-ismail",
    "د. جمانة إسماعيل",
    "Dr. Jumana Ismail",
    "مدرّسة — تنمية وتخطيط",
    "Lecturer — Development & planning",
    "مكتب 232",
    "نماذج النمو، الحسابات القومية، تخطيط القطاعات.",
    "Growth models, national accounts, sector planning.",
    "تعمل مع هيئة التخطيط والإحصاء على تطبيقات الحسابات ومشاريع التنمية للطلاب.",
    "Works with the Planning Authority on national-accounts applications and student development projects.",
    "MEA321,MEA322,MEA332",
  ),
  F(
    "f-kadmani",
    "د. نبيل قضماني",
    "Dr. Nabil Kadmani",
    "مدرّس — برمجة وتحليل بيانات",
    "Lecturer — Computing & data analysis",
    "مختبر 3",
    "Python و R للتحليل الاقتصادي، البيانات اللوحية، التعلّم الآلي التمهيدي.",
    "Python and R for economics, panel data, introductory machine learning.",
    "يشرف على مختبر الحوسبة ويضمن أن كل نموذج في البرنامج قابل لإعادة التشغيل.",
    "Runs the computing lab and insists that every model in the programme is reproducible.",
    "MEA141,MEA142,MEA242,MEA402",
  ),
  F(
    "f-atri",
    "د. هالة عطري",
    "Dr. Hala Atri",
    "مدرّسة — اقتصاد مفتوح",
    "Lecturer — Open-economy economics",
    "مكتب 208",
    "التجارة، سعر الصرف، التكتلات، الطاقة.",
    "Trade, exchange rates, blocs, energy.",
    "تدرّس العلاقات الدولية واقتصاد الطاقة، وتركّز على انفتاح الاقتصاد السوري.",
    "Teaches international economics and energy, with a focus on the openness of the Syrian economy.",
    "MEA331,MEA341,MEA431",
  ),
  F(
    "f-deeb",
    "أ.د. وائل ديب",
    "Prof. Wael Deeb",
    "رئيس اللجنة العلمية",
    "Chair of the scientific committee",
    "مكتب العمادة 12",
    "الاقتصاد الرياضي، تاريخ الفكر، منهجية البحث.",
    "Mathematical economics, history of thought, research methods.",
    "يرأس اللجنة العلمية للبرنامج ويدرّس منهجية البحث ومشروع التخرج.",
    "Chairs the programme’s scientific committee and teaches research methods and the graduation project.",
    "MEA101,MEA432,MEA491,MEA492",
  ),
];

const A = "f-harfoush";
const B = "f-abdelnour";
const C = "f-barakat";
const D = "f-ismail";

export const STUDENTS: Person[] = [
  // Alumni 2022–2026 (first cohort)
  S("s-alma", "ألما حرفوش", "Alma Harfoush", 5, "MEA2201", "2022–2026", A, "اهتمت بمحددات التضخم ونماذج VAR.", "Worked on inflation determinants and VAR models."),
  S("s-tamer", "تامر حلبي", "Tamer Halabi", 5, "MEA2202", "2022–2026", B, "بنى سيناريوهات إعادة إعمار مبسّطة.", "Built simplified reconstruction scenarios."),
  S("s-lina", "لينا قضماني", "Lina Kadmani", 5, "MEA2203", "2022–2026", A, "قيّمت كفاءة الإنفاق الاستثماري العام.", "Evaluated the efficiency of public investment."),
  S("s-rami", "رامي خوري", "Rami Khoury", 5, "MEA2204", "2022–2026", D, "نموذج مدخلات-مخرجات للصناعة التحويلية.", "An input–output model of manufacturing."),
  S("s-nidaa", "نداء إسماعيل", "Nidaa Ismail", 5, "MEA2205", "2022–2026", B, "دراسة سياسات الدعم وأثرها في الأسعار.", "Studied subsidy policy and price effects."),
  S("s-samer", "سامر ديب", "Samer Deeb", 5, "MEA2206", "2022–2026", A, "نمذجة سوق العمل والأجور الحقيقية.", "Modelled the labour market and real wages."),
  S("s-hind", "هند بركات", "Hind Barakat", 5, "MEA2207", "2022–2026", C, "تحليل مؤشرات الاقتصاد الكلّي 2000–2024.", "Macro indicator analysis, 2000–2024."),
  S("s-jad", "جاد عطري", "Jad Atri", 5, "MEA2208", "2022–2026", D, "سيناريوهات الطاقة والنمو.", "Energy and growth scenarios."),
  S("s-maya", "مايا شاهين", "Maya Shaheen", 5, "MEA2209", "2022–2026", B, "قياس أثر السياسة النقدية في سعر الصرف.", "Measured monetary-policy effects on the exchange rate."),

  // Year 4 — 2023–2027
  S("s-y4-1", "كريم نصور", "Karim Nassour", 4, "MEA2301", "2023–2027", A, "يعمل على نموذج لَوحي للبنوك الخاصة.", "Building a panel model of private banks."),
  S("s-y4-2", "تالا فرحات", "Tala Farhat", 4, "MEA2302", "2023–2027", B, "تهتم بديناميك الدين العام.", "Working on public-debt dynamics."),
  S("s-y4-3", "ميسرة خوري", "Maysara Khoury", 4, "MEA2303", "2023–2027", D, "تدرس سلاسل الإمداد الزراعية.", "Studying agricultural supply chains."),
  S("s-y4-4", "جود حلبي", "Joud Halabi", 4, "MEA2304", "2023–2027", C, "تحليل البطالة الإقليمية.", "Regional unemployment analysis."),
  S("s-y4-5", "ساني قضماني", "Sani Kadmani", 4, "MEA2305", "2023–2027", A, "تعلّم آلي تمهيدي للتنبؤ بالمؤشرات.", "Introductory ML for indicator forecasts."),
  S("s-y4-6", "هدى بركات", "Huda Barakat", 4, "MEA2306", "2023–2027", B, "نمذجة الاستهلاك العائلي.", "Household consumption modelling."),
  S("s-y4-7", "نزار ديب", "Nizar Deeb", 4, "MEA2307", "2023–2027", A, "تقييم برامج التشغيل.", "Evaluating employment programmes."),
  S("s-y4-8", "لمى عطري", "Lama Atri", 4, "MEA2308", "2023–2027", D, "اقتصاد الطاقة المتجددة.", "Renewable-energy economics."),

  // Year 3 — 2024–2028
  S("s-y3-1", "لين نصور", "Lynn Nassour", 3, "MEA2401", "2024–2028", C, "تهتم بالسلاسل الزمنية للتضخم.", "Interested in inflation time series."),
  S("s-y3-2", "باسل حرفوش", "Basel Harfoush", 3, "MEA2402", "2024–2028", A, "يبني أدوات انحدار في R.", "Building regression tooling in R."),
  S("s-y3-3", "سلام خوري", "Salam Khoury", 3, "MEA2403", "2024–2028", B, "تقرأ نماذج النمو المبسّطة.", "Reading small growth models."),
  S("s-y3-4", "عُلا إسماعيل", "Ola Ismail", 3, "MEA2404", "2024–2028", D, "حسابات قومية تطبيقية.", "Applied national accounts."),
  S("s-y3-5", "فراس حلبي", "Firas Halabi", 3, "MEA2405", "2024–2028", A, "بيانات لوحية للمصارف.", "Banking panel data."),
  S("s-y3-6", "رهام ديب", "Reham Deeb", 3, "MEA2406", "2024–2028", C, "عينات وتصميم استبيان.", "Sampling and survey design."),
  S("s-y3-7", "وسيم قضماني", "Wasim Kadmani", 3, "MEA2407", "2024–2028", B, "اقتصاد مفتوح تمهيدي.", "Introductory open-economy work."),
  S("s-y3-8", "دانا شاهين", "Dana Shaheen", 3, "MEA2408", "2024–2028", D, "دراسات جدوى قطاع الخدمات.", "Feasibility work on services."),

  // Year 2 — 2025–2029
  S("s-y2-1", "يوسف بركات", "Youssef Barakat", 2, "MEA2501", "2025–2029", C, "يتقدّم في الإحصاء الاستدلالي.", "Advancing in inferential statistics."),
  S("s-y2-2", "نور فرحات", "Nour Farhat", 2, "MEA2502", "2025–2029", A, "تهتم بالتحليل الجزئي.", "Drawn to microeconomic analysis."),
  S("s-y2-3", "إياد نصور", "Iyad Nassour", 2, "MEA2503", "2025–2029", B, "يتدرّب على R.", "Training in R."),
  S("s-y2-4", "سيلفا خوري", "Silva Khoury", 2, "MEA2504", "2025–2029", D, "مالية عامة تمهيدية.", "Introductory public finance."),
  S("s-y2-5", "غيث حلبي", "Ghaith Halabi", 2, "MEA2505", "2025–2029", A, "جبر خطي وتطبيقاته.", "Linear algebra and applications."),
  S("s-y2-6", "مجد إسماعيل", "Majd Ismail", 2, "MEA2506", "2025–2029", C, "مختبر الإحصاء.", "Statistics lab."),
  S("s-y2-7", "راما ديب", "Rama Deeb", 2, "MEA2507", "2025–2029", B, "تحليل كلّي تمهيدي.", "Introductory macro analysis."),
  S("s-y2-8", "ليث عطري", "Laith Atri", 2, "MEA2508", "2025–2029", D, "نقود ومصارف.", "Money and banking."),

  // Year 1 — 2026–2030
  S("s-y1-1", "سارة حرفوش", "Sara Harfoush", 1, "MEA2601", "2026–2030", A, "دفعة هذا العام — مدخل إلى النمذجة.", "This year’s intake — introduction to modelling."),
  S("s-y1-2", "عمر قضماني", "Omar Kadmani", 1, "MEA2602", "2026–2030", C, "خلفية رياضية من المركز الوطني للمتميزين.", "Mathematical background from the NCD."),
  S("s-y1-3", "ميساء حلبي", "Maysa Halabi", 1, "MEA2603", "2026–2030", B, "اهتمام مبكر بالبيانات.", "Early interest in data."),
  S("s-y1-4", "حسام خوري", "Hussam Khoury", 1, "MEA2604", "2026–2030", D, "يتعلّم Python في المختبر.", "Learning Python in the lab."),
  S("s-y1-5", "جنى نصور", "Jana Nassour", 1, "MEA2605", "2026–2030", C, "إحصاء وصفي وتطبيقات.", "Descriptive statistics and applications."),
  S("s-y1-6", "طلال بركات", "Talal Barakat", 1, "MEA2606", "2026–2030", A, "مبادئ الاقتصاد والمحاسبة.", "Principles of economics and accounting."),
  S("s-y1-7", "رنيم إسماعيل", "Raneem Ismail", 1, "MEA2607", "2026–2030", B, "لغة أجنبية اقتصادية.", "Economic English."),
  S("s-y1-8", "زياد شاهين", "Ziad Shaheen", 1, "MEA2608", "2026–2030", D, "مدخل إلى النمذجة في الفصل الثاني.", "Introduction to modelling in semester two."),
  S("s-y1-9", "لارا ديب", "Lara Deeb", 1, "MEA2609", "2026–2030", C, "تاسعة طلاب السنة الأولى هذا العام.", "Ninth student in this year’s first year."),
];

export const PEOPLE: Person[] = [...FACULTY, ...STUDENTS];
