/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppCharterRouteImport } from './routes/_app/charter'
import { Route as AppCurriculumRouteImport } from './routes/_app/curriculum'
import { Route as AppFacultyRouteImport } from './routes/_app/faculty'
import { Route as AppGradesRouteImport } from './routes/_app/grades'
import { Route as AppJoinRouteImport } from './routes/_app/join'
import { Route as AppMissionRouteImport } from './routes/_app/mission'
import { Route as AppNoticesRouteImport } from './routes/_app/notices'
import { Route as AppPeopleRouteImport } from './routes/_app/people'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppRegistryRouteImport } from './routes/_app/registry'
import { Route as AppResourcesRouteImport } from './routes/_app/resources'
import { Route as AppCoursesCodeRouteImport } from './routes/_app/courses.$code'
import { Route as AppNoticesIdRouteImport } from './routes/_app/notices.$id'
import { Route as AppPeopleIdRouteImport } from './routes/_app/people.$id'
import { Route as AppProjectsIdRouteImport } from './routes/_app/projects.$id'
import { Route as AppYearsYearRouteImport } from './routes/_app/years.$year'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppCharterRoute = AppCharterRouteImport.update({
  id: '/charter',
  path: '/charter',
  getParentRoute: () => AppRoute,
} as any)
const AppCurriculumRoute = AppCurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => AppRoute,
} as any)
const AppFacultyRoute = AppFacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => AppRoute,
} as any)
const AppGradesRoute = AppGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => AppRoute,
} as any)
const AppJoinRoute = AppJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AppRoute,
} as any)
const AppMissionRoute = AppMissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => AppRoute,
} as any)
const AppNoticesRoute = AppNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleRoute = AppPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppRegistryRoute = AppRegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesRoute = AppResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesCodeRoute = AppCoursesCodeRouteImport.update({
  id: '/courses/$code',
  path: '/courses/$code',
  getParentRoute: () => AppRoute,
} as any)
const AppNoticesIdRoute = AppNoticesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppNoticesRoute,
} as any)
const AppPeopleIdRoute = AppPeopleIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPeopleRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppYearsYearRoute = AppYearsYearRouteImport.update({
  id: '/years/$year',
  path: '/years/$year',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/calendar': typeof AppCalendarRoute
  '/charter': typeof AppCharterRoute
  '/curriculum': typeof AppCurriculumRoute
  '/faculty': typeof AppFacultyRoute
  '/grades': typeof AppGradesRoute
  '/join': typeof AppJoinRoute
  '/mission': typeof AppMissionRoute
  '/notices': typeof AppNoticesRouteWithChildren
  '/people': typeof AppPeopleRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/registry': typeof AppRegistryRoute
  '/resources': typeof AppResourcesRoute
  '/courses/$code': typeof AppCoursesCodeRoute
  '/notices/$id': typeof AppNoticesIdRoute
  '/people/$id': typeof AppPeopleIdRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/years/$year': typeof AppYearsYearRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/calendar': typeof AppCalendarRoute
  '/charter': typeof AppCharterRoute
  '/curriculum': typeof AppCurriculumRoute
  '/faculty': typeof AppFacultyRoute
  '/grades': typeof AppGradesRoute
  '/join': typeof AppJoinRoute
  '/mission': typeof AppMissionRoute
  '/notices': typeof AppNoticesRouteWithChildren
  '/people': typeof AppPeopleRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/registry': typeof AppRegistryRoute
  '/resources': typeof AppResourcesRoute
  '/': typeof AppIndexRoute
  '/courses/$code': typeof AppCoursesCodeRoute
  '/notices/$id': typeof AppNoticesIdRoute
  '/people/$id': typeof AppPeopleIdRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/years/$year': typeof AppYearsYearRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/charter': typeof AppCharterRoute
  '/_app/curriculum': typeof AppCurriculumRoute
  '/_app/faculty': typeof AppFacultyRoute
  '/_app/grades': typeof AppGradesRoute
  '/_app/join': typeof AppJoinRoute
  '/_app/mission': typeof AppMissionRoute
  '/_app/notices': typeof AppNoticesRouteWithChildren
  '/_app/people': typeof AppPeopleRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/registry': typeof AppRegistryRoute
  '/_app/resources': typeof AppResourcesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/courses/$code': typeof AppCoursesCodeRoute
  '/_app/notices/$id': typeof AppNoticesIdRoute
  '/_app/people/$id': typeof AppPeopleIdRoute
  '/_app/projects/$id': typeof AppProjectsIdRoute
  '/_app/years/$year': typeof AppYearsYearRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/calendar'
    | '/charter'
    | '/curriculum'
    | '/faculty'
    | '/grades'
    | '/join'
    | '/mission'
    | '/notices'
    | '/people'
    | '/profile'
    | '/projects'
    | '/registry'
    | '/resources'
    | '/courses/$code'
    | '/notices/$id'
    | '/people/$id'
    | '/projects/$id'
    | '/years/$year'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/calendar'
    | '/charter'
    | '/curriculum'
    | '/faculty'
    | '/grades'
    | '/join'
    | '/mission'
    | '/notices'
    | '/people'
    | '/profile'
    | '/projects'
    | '/registry'
    | '/resources'
    | '/'
    | '/courses/$code'
    | '/notices/$id'
    | '/people/$id'
    | '/projects/$id'
    | '/years/$year'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/calendar'
    | '/_app/charter'
    | '/_app/curriculum'
    | '/_app/faculty'
    | '/_app/grades'
    | '/_app/join'
    | '/_app/mission'
    | '/_app/notices'
    | '/_app/people'
    | '/_app/profile'
    | '/_app/projects'
    | '/_app/registry'
    | '/_app/resources'
    | '/_app/'
    | '/_app/courses/$code'
    | '/_app/notices/$id'
    | '/_app/people/$id'
    | '/_app/projects/$id'
    | '/_app/years/$year'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/charter': {
      id: '/_app/charter'
      path: '/charter'
      fullPath: '/charter'
      preLoaderRoute: typeof AppCharterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/curriculum': {
      id: '/_app/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof AppCurriculumRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/faculty': {
      id: '/_app/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof AppFacultyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grades': {
      id: '/_app/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof AppGradesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/join': {
      id: '/_app/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof AppJoinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mission': {
      id: '/_app/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof AppMissionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notices': {
      id: '/_app/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof AppNoticesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people': {
      id: '/_app/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AppPeopleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/registry': {
      id: '/_app/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof AppRegistryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources': {
      id: '/_app/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AppResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses/$code': {
      id: '/_app/courses/$code'
      path: '/courses/$code'
      fullPath: '/courses/$code'
      preLoaderRoute: typeof AppCoursesCodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notices/$id': {
      id: '/_app/notices/$id'
      path: '/$id'
      fullPath: '/notices/$id'
      preLoaderRoute: typeof AppNoticesIdRouteImport
      parentRoute: typeof AppNoticesRoute
    }
    '/_app/people/$id': {
      id: '/_app/people/$id'
      path: '/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof AppPeopleIdRouteImport
      parentRoute: typeof AppPeopleRoute
    }
    '/_app/projects/$id': {
      id: '/_app/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/years/$year': {
      id: '/_app/years/$year'
      path: '/years/$year'
      fullPath: '/years/$year'
      preLoaderRoute: typeof AppYearsYearRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppNoticesRouteChildren {
  AppNoticesIdRoute: typeof AppNoticesIdRoute
}

const AppNoticesRouteChildren: AppNoticesRouteChildren = {
  AppNoticesIdRoute: AppNoticesIdRoute,
}

const AppNoticesRouteWithChildren = AppNoticesRoute._addFileChildren(
  AppNoticesRouteChildren,
)

interface AppPeopleRouteChildren {
  AppPeopleIdRoute: typeof AppPeopleIdRoute
}

const AppPeopleRouteChildren: AppPeopleRouteChildren = {
  AppPeopleIdRoute: AppPeopleIdRoute,
}

const AppPeopleRouteWithChildren = AppPeopleRoute._addFileChildren(
  AppPeopleRouteChildren,
)

interface AppProjectsRouteChildren {
  AppProjectsIdRoute: typeof AppProjectsIdRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsIdRoute: AppProjectsIdRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppCharterRoute: typeof AppCharterRoute
  AppCurriculumRoute: typeof AppCurriculumRoute
  AppFacultyRoute: typeof AppFacultyRoute
  AppGradesRoute: typeof AppGradesRoute
  AppJoinRoute: typeof AppJoinRoute
  AppMissionRoute: typeof AppMissionRoute
  AppNoticesRoute: typeof AppNoticesRouteWithChildren
  AppPeopleRoute: typeof AppPeopleRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppRegistryRoute: typeof AppRegistryRoute
  AppResourcesRoute: typeof AppResourcesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCoursesCodeRoute: typeof AppCoursesCodeRoute
  AppYearsYearRoute: typeof AppYearsYearRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppCharterRoute: AppCharterRoute,
  AppCurriculumRoute: AppCurriculumRoute,
  AppFacultyRoute: AppFacultyRoute,
  AppGradesRoute: AppGradesRoute,
  AppJoinRoute: AppJoinRoute,
  AppMissionRoute: AppMissionRoute,
  AppNoticesRoute: AppNoticesRouteWithChildren,
  AppPeopleRoute: AppPeopleRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppRegistryRoute: AppRegistryRoute,
  AppResourcesRoute: AppResourcesRoute,
  AppIndexRoute: AppIndexRoute,
  AppCoursesCodeRoute: AppCoursesCodeRoute,
  AppYearsYearRoute: AppYearsYearRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
